FROM registry.fedoraproject.org/fedora-toolbox:35

WORKDIR /

# Toolbox necessary headers

ENV NAME=default-toolbox VERSION=35
LABEL com.github.containers.toolbox="true" \
      com.github.debarshiray.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="This is a default image to use in toolbox containers." \
      maintainer="Arthur Soulié EPITECH promotion 2024 <arthur.soulie@tuta.io>"


# Packages installation

COPY . .
RUN dnf upgrade -y
RUN dnf install $(< ./assets/packages) -y
